# Generated by Django 6.0.6 on 2026-07-01 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers_alter_user_role_curatorprofile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listenerprofile',
            name='favorite_genres',
        ),
        migrations.RemoveField(
            model_name='listenerprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='CuratorProfile',
        ),
        migrations.DeleteModel(
            name='ListenerProfile',
        ),
    ]
