# Generated by Django 6.0.6 on 2026-07-01 13:32

import accounts.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_listenerprofile_favorite_genres_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.managers.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('listener', 'Listener'), ('curator', 'Curator'), ('admin', 'Admin')], default='listener', max_length=20),
        ),
    ]
