# Generated by Django 6.0.5 on 2026-06-02 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listeners', '0001_initial'),
    ]

    operations = [
    ]
