# Generated by Django 6.0.5 on 2026-06-02 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listeners', '0002_update_models'),
    ]

    operations = [
    ]
