# Generated by Django 6.0.5 on 2026-06-02 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('listeners', '0004_update_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='listener',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playlist',
            name='tracks',
            field=models.ManyToManyField(blank=True, related_name='playlists', to='catalog.track'),
        ),
        migrations.CreateModel(
            name='MonthlyListeningStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seconds_listened', models.IntegerField(default=0)),
                ('month', models.DateField(db_index=True)),
                ('listener', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_statistics', to=settings.AUTH_USER_MODEL)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_statistics', to='catalog.track')),
            ],
            options={
                'unique_together': {('listener', 'track', 'month')},
            },
        ),
        migrations.DeleteModel(
            name='Listener',
        ),
    ]
