# Generated by Django 6.0.5 on 2026-06-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listeners', '0005_alter_playlist_listener_playlist_tracks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
