# Generated by Django 6.0.6 on 2026-06-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listeners', '0006_playlist_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='title',
            field=models.CharField(default='New playlist', max_length=100),
        ),
    ]
