# Generated by Django 6.0.6 on 2026-06-18 20:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listeners', '0007_playlist_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_playlists', to=settings.AUTH_USER_MODEL),
        ),
    ]
