# Generated by Django 6.0.6 on 2026-06-20 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listeners', '0008_playlist_saved_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='name',
        ),
    ]
