# Generated by Django 6.0.6 on 2026-07-02 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listeners', '0010_alter_monthlylisteningstatistic_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlylisteningstatistic',
            options={'permissions': [('log_playback', 'Can log playback / listening statistics')]},
        ),
    ]
