# Generated by Django 6.0.5 on 2026-06-02 13:59

import catalog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('cover_file', models.ImageField(blank=True, null=True, upload_to=catalog.models.album_cover_upload_path)),
                ('release_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('stage_name', models.CharField(max_length=100)),
                ('biography', models.TextField()),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AlbumTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_number', models.IntegerField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.album')),
            ],
            options={
                'ordering': ['track_number'],
            },
        ),
        migrations.AddField(
            model_name='album',
            name='artists',
            field=models.ManyToManyField(blank=True, related_name='albums', to='catalog.artist'),
        ),
        migrations.AddField(
            model_name='album',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='albums', to='catalog.genre'),
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('explicit', models.BooleanField()),
                ('audio_file', models.FileField(max_length=500, upload_to=catalog.models.track_upload_path)),
                ('single_cover', models.ImageField(blank=True, null=True, upload_to=catalog.models.track_cover_upload_path)),
                ('release_date', models.DateField()),
                ('albums', models.ManyToManyField(blank=True, related_name='tracks', through='catalog.AlbumTrack', to='catalog.album')),
                ('artists', models.ManyToManyField(blank=True, related_name='tracks', to='catalog.artist')),
            ],
        ),
        migrations.AddField(
            model_name='albumtrack',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.track'),
        ),
        migrations.AlterUniqueTogether(
            name='albumtrack',
            unique_together={('album', 'track_number')},
        ),
    ]
