# Generated by Django 6.0.5 on 2026-06-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='tracks', to='catalog.genre'),
        ),
    ]
