# Generated by Django 6.0.6 on 2026-06-29 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_track_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='name',
        ),
    ]
