# Generated by Django 6.0.6 on 2026-07-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_album_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='email',
        ),
        migrations.AlterField(
            model_name='artist',
            name='biography',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='stage_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
