# Generated by Django 6.0.6 on 2026-07-01 15:47

from django.db import migrations

def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    listeners_group, _ = Group.objects.get_or_create(name='Listeners')
    curators_group, _ = Group.objects.get_or_create(name='Curators')

    listeners_group.permissions.set(
        Permission.objects.filter(
            content_type__app_label='catalog',
            codename__startswith='view_'
        )
    )

    curators_group.permissions.set(
        Permission.objects.filter(
            content_type__app_label='catalog',
            codename__in=[
                'view_artist', 'add_artist', 'change_artist', 'delete_artist',
                'view_album', 'add_album', 'change_album', 'delete_album',
                'view_track', 'add_track', 'change_track', 'delete_track',
                'view_genre', 'add_genre', 'change_genre', 'delete_genre',
            ]
        )
    )

class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]