# Generated by Django 6.0.6 on 2026-07-01 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_artist_email_alter_artist_biography_and_more'),
        ('catalog', '0005_auto_20260701_1747'),
    ]

    operations = [
    ]
