# Generated by Django 6.0.6 on 2026-07-05 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20260701_2159'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='genre',
            unique_together={('name',)},
        ),
    ]
